-- ─── Zonas Geográficas — zonas dibujadas en mapa ─────────────────────────
-- Tabla independiente de zona/sectores/fincas.
-- Almacena geometría como GeoJSON (jsonb), sin PostGIS.
-- Cada zona pertenece a una empresa (multi-tenant).

create table if not exists public.zonas_geograficas (
  id          bigint generated by default as identity primary key,
  empresa_id  bigint not null references empresas(id) on delete cascade,
  nombre      text not null,
  descripcion text,
  color       text not null default '#2563eb'::text,
  tipo        text not null default 'personalizada'::text,
  estado      text not null default 'activa'::text,
  geojson     jsonb not null,
  area_sqm    numeric,
  created_by  bigint not null references usuarios(id) on delete restrict,
  updated_by  bigint references usuarios(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  archived_at timestamptz
);

-- Índices
create index idx_zonas_geograficas_empresa on public.zonas_geograficas(empresa_id);
create index idx_zonas_geograficas_estado  on public.zonas_geograficas(estado);

-- updated_at trigger
create or replace function set_zonas_geograficas_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists zonas_geograficas_updated_at_trigger on public.zonas_geograficas;
create trigger zonas_geograficas_updated_at_trigger
  before update on public.zonas_geograficas
  for each row execute function set_zonas_geograficas_updated_at();

-- ─── RLS ─────────────────────────────────────────────────────────────────
alter table public.zonas_geograficas enable row level security;

-- SELECT: usuarios ven zonas de su empresa
drop policy if exists zonas_geograficas_select on public.zonas_geograficas;
create policy zonas_geograficas_select
on public.zonas_geograficas for select
using (empresa_id = public.current_empresa_id());

-- INSERT: admin/director pueden crear en su empresa
drop policy if exists zonas_geograficas_insert on public.zonas_geograficas;
create policy zonas_geograficas_insert
on public.zonas_geograficas for insert
with check (
  empresa_id = public.current_empresa_id()
  and public.is_admin_or_director()
);

-- UPDATE: admin/director pueden modificar en su empresa
drop policy if exists zonas_geograficas_update on public.zonas_geograficas;
create policy zonas_geograficas_update
on public.zonas_geograficas for update
using (empresa_id = public.current_empresa_id() and public.is_admin_or_director())
with check (empresa_id = public.current_empresa_id() and public.is_admin_or_director());

-- DELETE: admin/director pueden eliminar en su empresa
drop policy if exists zonas_geograficas_delete on public.zonas_geograficas;
create policy zonas_geograficas_delete
on public.zonas_geograficas for delete
using (empresa_id = public.current_empresa_id() and public.is_admin_or_director());
