-- Activity tracking for Desarrollo metrics.
-- rendimiento stores goals; actividad_desarrollo stores the real actions that
-- fill the progress rings.

create table if not exists public.rendimiento (
  id bigint generated by default as identity primary key,
  agente_id bigint not null references public.usuarios (id) on delete cascade,
  anio integer not null,
  mes integer not null default 0,
  facturado numeric not null default 0,
  objetivo_facturado numeric not null default 100000,
  encargos integer not null default 0,
  objetivo_encargos integer not null default 10,
  ventas integer not null default 0,
  objetivo_ventas integer not null default 5,
  contactos integer not null default 0,
  objetivo_contactos integer not null default 50,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint rendimiento_mes_check check (mes between 0 and 12)
);

create table if not exists public.actividad_desarrollo (
  id bigint generated by default as identity primary key,
  agente_id bigint not null references public.usuarios (id) on delete cascade,
  actor_user_id bigint references public.usuarios (id) on delete set null,
  empresa_id bigint references public.empresas (id) on delete set null,
  equipo_id bigint references public.equipos (id) on delete set null,
  metric text not null,
  action text not null,
  source_table text not null,
  source_id bigint not null,
  value numeric not null default 1,
  occurred_at timestamptz not null default timezone('utc'::text, now()),
  metadata jsonb not null default '{}'::jsonb,
  constraint actividad_desarrollo_metric_check
    check (metric in ('facturado', 'encargos', 'ventas', 'contactos'))
);

create index if not exists actividad_desarrollo_agente_period_idx
on public.actividad_desarrollo (agente_id, occurred_at);

create index if not exists actividad_desarrollo_empresa_period_idx
on public.actividad_desarrollo (empresa_id, occurred_at);

create unique index if not exists actividad_desarrollo_source_metric_action_key
on public.actividad_desarrollo (source_table, source_id, metric, action);

-- Ensure one objetivos row per agent and period.
with ranked as (
  select
    id,
    row_number() over (
      partition by agente_id, anio, mes
      order by id
    ) as rn
  from public.rendimiento
)
delete from public.rendimiento r
using ranked
where r.id = ranked.id
  and ranked.rn > 1;

create unique index if not exists rendimiento_agente_anio_mes_key
on public.rendimiento (agente_id, anio, mes);

alter table public.usuarios
  add column if not exists supervisor_id bigint
  references public.usuarios (id) on delete set null;

create or replace function public.get_supervised_user_ids()
returns setof bigint
language sql
stable
security definer
set search_path = public
as $$
  select id
  from public.usuarios
  where supervisor_id = public.current_usuario_id()
$$;

create or replace function public.can_view_agent_metrics(target_agente_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case
    when auth.uid() is null then false
    when target_agente_id = public.current_usuario_id() then true
    when public.current_user_role() in ('Administrador', 'Director')
      and exists (
        select 1
        from public.usuarios u
        where u.id = target_agente_id
          and u.empresa_id = public.current_empresa_id()
      ) then true
    when public.current_user_role() = 'Responsable'
      and exists (
        select 1
        from public.get_supervised_user_ids() as supervised(id)
        where supervised.id = target_agente_id
      ) then true
    else false
  end
$$;

create or replace function public.can_manage_agent_objectives(target_agente_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case
    when auth.uid() is null then false
    when public.current_user_role() not in ('Administrador', 'Director') then false
    when exists (
      select 1
      from public.usuarios u
      where u.id = target_agente_id
        and u.empresa_id = public.current_empresa_id()
    ) then true
    else false
  end
$$;

alter table public.rendimiento enable row level security;
alter table public.actividad_desarrollo enable row level security;

drop policy if exists rendimiento_select_visible on public.rendimiento;
create policy rendimiento_select_visible
on public.rendimiento
for select
using (public.can_view_agent_metrics(agente_id));

drop policy if exists rendimiento_insert_objectives on public.rendimiento;
create policy rendimiento_insert_objectives
on public.rendimiento
for insert
with check (public.can_manage_agent_objectives(agente_id));

drop policy if exists rendimiento_update_objectives on public.rendimiento;
create policy rendimiento_update_objectives
on public.rendimiento
for update
using (public.can_manage_agent_objectives(agente_id))
with check (public.can_manage_agent_objectives(agente_id));

drop policy if exists rendimiento_delete_objectives on public.rendimiento;
create policy rendimiento_delete_objectives
on public.rendimiento
for delete
using (public.can_manage_agent_objectives(agente_id));

create or replace function public.protect_rendimiento_actuals()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return new;
  end if;

  if tg_op = 'INSERT' then
    if coalesce(new.facturado, 0) <> 0
      or coalesce(new.encargos, 0) <> 0
      or coalesce(new.ventas, 0) <> 0
      or coalesce(new.contactos, 0) <> 0 then
      raise exception 'Los valores reales se calculan desde actividad_desarrollo.';
    end if;
  elsif tg_op = 'UPDATE' then
    if old.facturado is distinct from new.facturado
      or old.encargos is distinct from new.encargos
      or old.ventas is distinct from new.ventas
      or old.contactos is distinct from new.contactos then
      raise exception 'Los valores reales se calculan desde actividad_desarrollo.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_rendimiento_protect_actuals on public.rendimiento;
create trigger trg_rendimiento_protect_actuals
before insert or update on public.rendimiento
for each row
execute function public.protect_rendimiento_actuals();

drop policy if exists actividad_desarrollo_select_visible on public.actividad_desarrollo;
create policy actividad_desarrollo_select_visible
on public.actividad_desarrollo
for select
using (public.can_view_agent_metrics(agente_id));

create or replace function public.insert_desarrollo_activity(
  target_agente_id bigint,
  target_actor_user_id bigint,
  target_metric text,
  target_action text,
  target_source_table text,
  target_source_id bigint,
  target_value numeric default 1,
  target_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_user record;
begin
  if target_agente_id is null then
    return;
  end if;

  select id, empresa_id, equipo_id
  into target_user
  from public.usuarios
  where id = target_agente_id
  limit 1;

  if not found then
    return;
  end if;

  insert into public.actividad_desarrollo (
    agente_id,
    actor_user_id,
    empresa_id,
    equipo_id,
    metric,
    action,
    source_table,
    source_id,
    value,
    metadata
  )
  values (
    target_user.id,
    target_actor_user_id,
    target_user.empresa_id,
    target_user.equipo_id,
    target_metric,
    target_action,
    target_source_table,
    target_source_id,
    coalesce(target_value, 1),
    coalesce(target_metadata, '{}'::jsonb)
  )
  on conflict (source_table, source_id, metric, action) do nothing;
end;
$$;

create or replace function public.track_pedido_desarrollo_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.insert_desarrollo_activity(
      coalesce(new.owner_user_id, public.current_usuario_id()),
      public.current_usuario_id(),
      'contactos',
      'pedido_creado',
      'pedidos',
      new.id,
      1,
      jsonb_build_object('nombre_cliente', new.nombre_cliente)
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_pedidos_desarrollo_activity on public.pedidos;
create trigger trg_pedidos_desarrollo_activity
after insert on public.pedidos
for each row
execute function public.track_pedido_desarrollo_activity();

create or replace function public.track_propiedad_desarrollo_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_agente_id bigint;
  previous_estado text;
  should_track boolean := false;
begin
  if tg_op = 'INSERT' then
    should_track := true;
  elsif old.estado is distinct from new.estado then
    previous_estado := old.estado;
    should_track := true;
  end if;

  if should_track then
    target_agente_id := coalesce(
      new.agente_asignado,
      new.owner_user_id,
      public.current_usuario_id()
    );

    if new.estado = 'encargo' then
      perform public.insert_desarrollo_activity(
        target_agente_id,
        public.current_usuario_id(),
        'encargos',
        'propiedad_encargo',
        'propiedades',
        new.id,
        1,
        jsonb_build_object('estado_anterior', previous_estado)
      );
    elsif new.estado = 'vendido' then
      perform public.insert_desarrollo_activity(
        target_agente_id,
        public.current_usuario_id(),
        'ventas',
        'propiedad_vendida',
        'propiedades',
        new.id,
        1,
        jsonb_build_object('estado_anterior', previous_estado)
      );
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_propiedades_desarrollo_activity on public.propiedades;
create trigger trg_propiedades_desarrollo_activity
after insert or update of estado, agente_asignado, owner_user_id on public.propiedades
for each row
execute function public.track_propiedad_desarrollo_activity();

create or replace function public.track_tarea_desarrollo_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.estado is distinct from new.estado
    and new.estado in ('completado', 'completada') then
    perform public.insert_desarrollo_activity(
      coalesce(new.owner_user_id, new.agente_asignado, public.current_usuario_id()),
      public.current_usuario_id(),
      'contactos',
      'tarea_completada',
      'tareas',
      new.id,
      1,
      jsonb_build_object('titulo', new.titulo)
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_tareas_desarrollo_activity on public.tareas;
create trigger trg_tareas_desarrollo_activity
after update of estado on public.tareas
for each row
execute function public.track_tarea_desarrollo_activity();
