create table if not exists public.empresas (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.equipos (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas (id) on delete cascade,
  nombre text not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  unique (empresa_id, nombre)
);

insert into public.empresas (id, nombre)
values (1, 'Empresa principal')
on conflict (id) do nothing;

insert into public.equipos (id, empresa_id, nombre)
values (1, 1, 'Equipo general')
on conflict (id) do nothing;

alter table public.usuarios
  add column if not exists rol text,
  add column if not exists empresa_id bigint,
  add column if not exists equipo_id bigint,
  add column if not exists estado text;

update public.usuarios
set rol = case lower(coalesce(puesto, ''))
  when 'administrador' then 'Administrador'
  when 'admin' then 'Administrador'
  when 'director' then 'Director'
  when 'responsable' then 'Responsable'
  when 'agente' then 'Agente'
  else 'Agente'
end
where rol is null;

update public.usuarios
set empresa_id = 1
where empresa_id is null;

update public.usuarios
set equipo_id = 1
where equipo_id is null;

update public.usuarios
set estado = 'active'
where estado is null;

alter table public.usuarios
  alter column rol set default 'Agente',
  alter column rol set not null,
  alter column estado set default 'active',
  alter column estado set not null;

alter table public.usuarios
  drop constraint if exists usuarios_rol_check;

alter table public.usuarios
  add constraint usuarios_rol_check
  check (rol in ('Administrador', 'Director', 'Responsable', 'Agente'));

alter table public.usuarios
  drop constraint if exists usuarios_estado_check;

alter table public.usuarios
  add constraint usuarios_estado_check
  check (estado in ('invited', 'active', 'disabled'));

alter table public.usuarios
  drop constraint if exists usuarios_empresa_id_fkey;

alter table public.usuarios
  add constraint usuarios_empresa_id_fkey
  foreign key (empresa_id) references public.empresas (id) on delete restrict;

alter table public.usuarios
  drop constraint if exists usuarios_equipo_id_fkey;

alter table public.usuarios
  add constraint usuarios_equipo_id_fkey
  foreign key (equipo_id) references public.equipos (id) on delete set null;

create unique index if not exists usuarios_auth_id_key
on public.usuarios (auth_id)
where auth_id is not null;

alter table public.agenda
  add column if not exists owner_user_id bigint,
  add column if not exists empresa_id bigint,
  add column if not exists equipo_id bigint,
  add column if not exists visibility text;

alter table public.pedidos
  add column if not exists owner_user_id bigint,
  add column if not exists empresa_id bigint,
  add column if not exists equipo_id bigint,
  add column if not exists visibility text;

alter table public.propiedades
  add column if not exists owner_user_id bigint,
  add column if not exists empresa_id bigint,
  add column if not exists equipo_id bigint,
  add column if not exists visibility text;

alter table public.tareas
  add column if not exists owner_user_id bigint,
  add column if not exists empresa_id bigint,
  add column if not exists equipo_id bigint,
  add column if not exists visibility text;

update public.agenda
set owner_user_id = coalesce(owner_user_id, user_id),
    empresa_id = coalesce(empresa_id, 1),
    equipo_id = coalesce(equipo_id, 1),
    visibility = coalesce(visibility, 'private');

update public.pedidos
set empresa_id = coalesce(empresa_id, 1),
    equipo_id = coalesce(equipo_id, 1),
    visibility = coalesce(visibility, 'company');

update public.propiedades
set owner_user_id = coalesce(owner_user_id, agente_asignado),
    empresa_id = coalesce(empresa_id, 1),
    equipo_id = coalesce(equipo_id, 1),
    visibility = coalesce(visibility, 'company');

update public.tareas
set owner_user_id = coalesce(owner_user_id, agente_asignado),
    empresa_id = coalesce(empresa_id, 1),
    equipo_id = coalesce(equipo_id, 1),
    visibility = coalesce(visibility, 'company');

alter table public.agenda
  alter column visibility set default 'private';

alter table public.pedidos
  alter column visibility set default 'private';

alter table public.propiedades
  alter column visibility set default 'private';

alter table public.tareas
  alter column visibility set default 'private';

alter table public.agenda
  alter column visibility set not null;

alter table public.pedidos
  alter column visibility set not null;

alter table public.propiedades
  alter column visibility set not null;

alter table public.tareas
  alter column visibility set not null;

alter table public.agenda
  drop constraint if exists agenda_visibility_check;

alter table public.agenda
  add constraint agenda_visibility_check
  check (visibility in ('private', 'team', 'company'));

alter table public.pedidos
  drop constraint if exists pedidos_visibility_check;

alter table public.pedidos
  add constraint pedidos_visibility_check
  check (visibility in ('private', 'team', 'company'));

alter table public.propiedades
  drop constraint if exists propiedades_visibility_check;

alter table public.propiedades
  add constraint propiedades_visibility_check
  check (visibility in ('private', 'team', 'company'));

alter table public.tareas
  drop constraint if exists tareas_visibility_check;

alter table public.tareas
  add constraint tareas_visibility_check
  check (visibility in ('private', 'team', 'company'));

alter table public.agenda
  drop constraint if exists agenda_owner_user_id_fkey,
  drop constraint if exists agenda_empresa_id_fkey,
  drop constraint if exists agenda_equipo_id_fkey;

alter table public.agenda
  add constraint agenda_owner_user_id_fkey foreign key (owner_user_id) references public.usuarios (id) on delete set null,
  add constraint agenda_empresa_id_fkey foreign key (empresa_id) references public.empresas (id) on delete set null,
  add constraint agenda_equipo_id_fkey foreign key (equipo_id) references public.equipos (id) on delete set null;

alter table public.pedidos
  drop constraint if exists pedidos_owner_user_id_fkey,
  drop constraint if exists pedidos_empresa_id_fkey,
  drop constraint if exists pedidos_equipo_id_fkey;

alter table public.pedidos
  add constraint pedidos_owner_user_id_fkey foreign key (owner_user_id) references public.usuarios (id) on delete set null,
  add constraint pedidos_empresa_id_fkey foreign key (empresa_id) references public.empresas (id) on delete set null,
  add constraint pedidos_equipo_id_fkey foreign key (equipo_id) references public.equipos (id) on delete set null;

alter table public.propiedades
  drop constraint if exists propiedades_owner_user_id_fkey,
  drop constraint if exists propiedades_empresa_id_fkey,
  drop constraint if exists propiedades_equipo_id_fkey;

alter table public.propiedades
  add constraint propiedades_owner_user_id_fkey foreign key (owner_user_id) references public.usuarios (id) on delete set null,
  add constraint propiedades_empresa_id_fkey foreign key (empresa_id) references public.empresas (id) on delete set null,
  add constraint propiedades_equipo_id_fkey foreign key (equipo_id) references public.equipos (id) on delete set null;

alter table public.tareas
  drop constraint if exists tareas_owner_user_id_fkey,
  drop constraint if exists tareas_empresa_id_fkey,
  drop constraint if exists tareas_equipo_id_fkey;

alter table public.tareas
  add constraint tareas_owner_user_id_fkey foreign key (owner_user_id) references public.usuarios (id) on delete set null,
  add constraint tareas_empresa_id_fkey foreign key (empresa_id) references public.empresas (id) on delete set null,
  add constraint tareas_equipo_id_fkey foreign key (equipo_id) references public.equipos (id) on delete set null;

create or replace function public.current_usuario_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select u.id
  from public.usuarios u
  where u.auth_id = auth.uid()
  limit 1
$$;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(u.rol, 'Agente')
  from public.usuarios u
  where u.auth_id = auth.uid()
  limit 1
$$;

create or replace function public.current_empresa_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select u.empresa_id
  from public.usuarios u
  where u.auth_id = auth.uid()
  limit 1
$$;

create or replace function public.current_equipo_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select u.equipo_id
  from public.usuarios u
  where u.auth_id = auth.uid()
  limit 1
$$;

create or replace function public.is_admin_or_director()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() in ('Administrador', 'Director'), false)
$$;

create or replace function public.can_access_scoped_row(
  row_owner_user_id bigint,
  row_empresa_id bigint,
  row_equipo_id bigint,
  row_visibility text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case
    when auth.uid() is null then false
    when public.is_admin_or_director() and row_empresa_id = public.current_empresa_id() then true
    when row_owner_user_id = public.current_usuario_id() then true
    when row_visibility = 'company' and row_empresa_id = public.current_empresa_id() then true
    when row_visibility = 'team'
      and row_empresa_id = public.current_empresa_id()
      and row_equipo_id = public.current_equipo_id() then true
    else false
  end
$$;

create or replace function public.can_manage_scoped_row(
  row_owner_user_id bigint,
  row_empresa_id bigint
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case
    when auth.uid() is null then false
    when row_owner_user_id = public.current_usuario_id() then true
    when public.current_user_role() in ('Administrador', 'Director', 'Responsable')
      and row_empresa_id = public.current_empresa_id() then true
    else false
  end
$$;

create or replace function public.apply_default_access_scope()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_record public.usuarios%rowtype;
begin
  if auth.uid() is null then
    return new;
  end if;

  select *
  into current_user_record
  from public.usuarios
  where auth_id = auth.uid()
  limit 1;

  if not found then
    return new;
  end if;

  if new.owner_user_id is null then
    new.owner_user_id := current_user_record.id;
  end if;

  if new.empresa_id is null then
    new.empresa_id := current_user_record.empresa_id;
  end if;

  if new.equipo_id is null then
    new.equipo_id := current_user_record.equipo_id;
  end if;

  if new.visibility is null then
    new.visibility := 'private';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_agenda_default_access_scope on public.agenda;
create trigger trg_agenda_default_access_scope
before insert or update on public.agenda
for each row
execute function public.apply_default_access_scope();

drop trigger if exists trg_pedidos_default_access_scope on public.pedidos;
create trigger trg_pedidos_default_access_scope
before insert or update on public.pedidos
for each row
execute function public.apply_default_access_scope();

drop trigger if exists trg_propiedades_default_access_scope on public.propiedades;
create trigger trg_propiedades_default_access_scope
before insert or update on public.propiedades
for each row
execute function public.apply_default_access_scope();

drop trigger if exists trg_tareas_default_access_scope on public.tareas;
create trigger trg_tareas_default_access_scope
before insert or update on public.tareas
for each row
execute function public.apply_default_access_scope();

alter table public.usuarios enable row level security;
alter table public.agenda enable row level security;
alter table public.pedidos enable row level security;
alter table public.propiedades enable row level security;
alter table public.tareas enable row level security;

drop policy if exists usuarios_select_same_company on public.usuarios;
create policy usuarios_select_same_company
on public.usuarios
for select
using (
  auth.uid() is not null
  and (
    id = public.current_usuario_id()
    or empresa_id = public.current_empresa_id()
  )
);

drop policy if exists agenda_select_scoped on public.agenda;
create policy agenda_select_scoped
on public.agenda
for select
using (public.can_access_scoped_row(owner_user_id, empresa_id, equipo_id, visibility));

drop policy if exists agenda_insert_scoped on public.agenda;
create policy agenda_insert_scoped
on public.agenda
for insert
with check (
  auth.uid() is not null
  and empresa_id = public.current_empresa_id()
  and owner_user_id = public.current_usuario_id()
);

drop policy if exists agenda_update_scoped on public.agenda;
create policy agenda_update_scoped
on public.agenda
for update
using (public.can_manage_scoped_row(owner_user_id, empresa_id))
with check (
  empresa_id = public.current_empresa_id()
  and (
    owner_user_id = public.current_usuario_id()
    or public.current_user_role() in ('Administrador', 'Director', 'Responsable')
  )
);

drop policy if exists agenda_delete_scoped on public.agenda;
create policy agenda_delete_scoped
on public.agenda
for delete
using (public.can_manage_scoped_row(owner_user_id, empresa_id));

drop policy if exists pedidos_select_scoped on public.pedidos;
create policy pedidos_select_scoped
on public.pedidos
for select
using (public.can_access_scoped_row(owner_user_id, empresa_id, equipo_id, visibility));

drop policy if exists pedidos_insert_scoped on public.pedidos;
create policy pedidos_insert_scoped
on public.pedidos
for insert
with check (
  auth.uid() is not null
  and empresa_id = public.current_empresa_id()
  and owner_user_id = public.current_usuario_id()
);

drop policy if exists pedidos_update_scoped on public.pedidos;
create policy pedidos_update_scoped
on public.pedidos
for update
using (public.can_manage_scoped_row(owner_user_id, empresa_id))
with check (
  empresa_id = public.current_empresa_id()
  and (
    owner_user_id = public.current_usuario_id()
    or public.current_user_role() in ('Administrador', 'Director', 'Responsable')
  )
);

drop policy if exists pedidos_delete_scoped on public.pedidos;
create policy pedidos_delete_scoped
on public.pedidos
for delete
using (public.can_manage_scoped_row(owner_user_id, empresa_id));

drop policy if exists propiedades_select_scoped on public.propiedades;
create policy propiedades_select_scoped
on public.propiedades
for select
using (public.can_access_scoped_row(owner_user_id, empresa_id, equipo_id, visibility));

drop policy if exists propiedades_insert_scoped on public.propiedades;
create policy propiedades_insert_scoped
on public.propiedades
for insert
with check (
  auth.uid() is not null
  and empresa_id = public.current_empresa_id()
  and owner_user_id = public.current_usuario_id()
);

drop policy if exists propiedades_update_scoped on public.propiedades;
create policy propiedades_update_scoped
on public.propiedades
for update
using (public.can_manage_scoped_row(owner_user_id, empresa_id))
with check (
  empresa_id = public.current_empresa_id()
  and (
    owner_user_id = public.current_usuario_id()
    or public.current_user_role() in ('Administrador', 'Director', 'Responsable')
  )
);

drop policy if exists propiedades_delete_scoped on public.propiedades;
create policy propiedades_delete_scoped
on public.propiedades
for delete
using (public.can_manage_scoped_row(owner_user_id, empresa_id));

drop policy if exists tareas_select_scoped on public.tareas;
create policy tareas_select_scoped
on public.tareas
for select
using (public.can_access_scoped_row(owner_user_id, empresa_id, equipo_id, visibility));

drop policy if exists tareas_insert_scoped on public.tareas;
create policy tareas_insert_scoped
on public.tareas
for insert
with check (
  auth.uid() is not null
  and empresa_id = public.current_empresa_id()
  and owner_user_id = public.current_usuario_id()
);

drop policy if exists tareas_update_scoped on public.tareas;
create policy tareas_update_scoped
on public.tareas
for update
using (public.can_manage_scoped_row(owner_user_id, empresa_id))
with check (
  empresa_id = public.current_empresa_id()
  and (
    owner_user_id = public.current_usuario_id()
    or public.current_user_role() in ('Administrador', 'Director', 'Responsable')
  )
);

drop policy if exists tareas_delete_scoped on public.tareas;
create policy tareas_delete_scoped
on public.tareas
for delete
using (public.can_manage_scoped_row(owner_user_id, empresa_id));
